sudo: false
language: ruby
cache: bundler
rvm:
  - 2.2.6
  - 2.3.0
  - 2.4.0
branches:
  only:
    - master

before_install:
  - rvm use @global
  - gem uninstall bundler -x
  - gem install bundler --version=1.13.7
  - bundler --version

addons:
  code_climate:
    repo_token: 8850bccc6911d74965627b1fafe753beb368fab00d33de0c7576c6598fc1220e

notifications:
  webhooks:
    urls:
      - http://publify_hook.ookook.fr/travisci
    on_success: always
    on_failure: never
    on_start: never
